//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductoServicesTest.ProductoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/ProductoService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPresentation {
            get {
                return this.IdPresentationField;
            }
            set {
                if ((this.IdPresentationField.Equals(value) != true)) {
                    this.IdPresentationField = value;
                    this.RaisePropertyChanged("IdPresentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameProduct {
            get {
                return this.NameProductField;
            }
            set {
                if ((object.ReferenceEquals(this.NameProductField, value) != true)) {
                    this.NameProductField = value;
                    this.RaisePropertyChanged("NameProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceProduct {
            get {
                return this.PriceProductField;
            }
            set {
                if ((this.PriceProductField.Equals(value) != true)) {
                    this.PriceProductField = value;
                    this.RaisePropertyChanged("PriceProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceSale {
            get {
                return this.PriceSaleField;
            }
            set {
                if ((this.PriceSaleField.Equals(value) != true)) {
                    this.PriceSaleField = value;
                    this.RaisePropertyChanged("PriceSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoWS.IProducto")]
    public interface IProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/crearProducto", ReplyAction="http://tempuri.org/IProducto/crearProductoResponse")]
        ProductoServicesTest.ProductoWS.Producto crearProducto(string nameProduct, int status, int idPresentacion, decimal priceProduct, System.DateTime dateCreated, decimal priceSale, System.DateTime expirationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/consultarProducto", ReplyAction="http://tempuri.org/IProducto/consultarProductoResponse")]
        ProductoServicesTest.ProductoWS.Producto consultarProducto(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoChannel : ProductoServicesTest.ProductoWS.IProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoClient : System.ServiceModel.ClientBase<ProductoServicesTest.ProductoWS.IProducto>, ProductoServicesTest.ProductoWS.IProducto {
        
        public ProductoClient() {
        }
        
        public ProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductoServicesTest.ProductoWS.Producto crearProducto(string nameProduct, int status, int idPresentacion, decimal priceProduct, System.DateTime dateCreated, decimal priceSale, System.DateTime expirationDate) {
            return base.Channel.crearProducto(nameProduct, status, idPresentacion, priceProduct, dateCreated, priceSale, expirationDate);
        }
        
        public ProductoServicesTest.ProductoWS.Producto consultarProducto(int id) {
            return base.Channel.consultarProducto(id);
        }
    }
}
